apiVersion: v1
kind: Pod
metadata:
  name: pod-for-logs
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: tomcat
      image: tomcat
      ports:
        - containerPort: 8080
